### ISSUE TITLE
Mechanical Press recipe for Chromatic Compound does not work.

### ISSUE THREAD

**Issue by GE0NE** [simibubi/Above-and-Beyond#87] opened 2021-11-09 12:31 UTC
The Basin will not accept more than one Magenta Paintball since they do not stack, making it impossible to add the 4 paintballs required for the recipe to work.

**Comment by Deadlock989** [comment] 2021-11-15 12:39
Confirmed - JEI lists this as a way of making Chromatic Compound but in fact you can't insert enough magenta balls into the basin for it to work. The mechanical crafters is the only way that works.

**Comment by UnderscoreKilburn** [comment] 2022-05-25 01:19
Mechanical crafters are the intended way to craft Chromatic Compound, looks like JEI showing a compacting recipe was a bug that was fixed in Create 0.3.2g.

**Closed by UnderscoreKilburn** 2022-05-25 01:19 UTC
