### ISSUE TITLE
Indestructible enchanted specialty fishing net breaks after 50 uses unless removed over and over

### ISSUE THREAD

**Issue by Ciruttai** [simibubi/Above-and-Beyond#125] opened 2021-11-14 06:14 UTC
![destructible indestructible](https://user-images.githubusercontent.com/94278601/141669959-8430a225-82c8-48f7-a5b5-799f1b2b19d8.png)
as you can see, indescructible specialty fishing nets lose durability when being used at all.

**Comment by Kevin-Marsh** [comment] 2021-11-14 21:00
The Indestructible enchantment is added by forbidden and arcanus. It is a bit of a misnomer since the way that it works is that the enchanted item still loses durability but constantly repairs itself when you have it. It would probably be up to them to fix it.

**Comment by Ciruttai** [comment] 2021-11-14 21:03
maybe they should not make items that do not stay in the player's inventory capable of being placed in a scenario where it loses durability, do the items used in create machines constantly lose durability when they are marked as indestructible too? because if so i'll just stop playing the pack, thank you! <3

**Comment by Ciruttai** [comment] 2021-11-14 22:54
this needs to be either fixed or removed, there's no point in having it enchantable with an enchantment that only works when you put it in your inventory every 49 uses.

**Comment by GE0NE** [comment] 2021-11-15 13:11
Duplicate of #85

**Comment by Ciruttai** [comment] 2021-11-17 09:33
it's not a duplicate, it's a different item, you mentioned a sediment strainer this is specialty fishing net.

**Comment by GoliathX211** [comment] 2021-11-17 14:34
It is indeed a duplicate because it is the same mod working in the exact same way with Forbidden and Arcanus’ Indestructible enchantment. I assume that they couldn’t just have it add the unbreakable NBT tag because you could grindstone the item afterwards and still have the item as unbreakable. Not sure how they (creators of Forbidden and Arcanus) could go about fixing it other than changing the functionality of the enchantment. I am able to say with confidence that the indestructible enchantment works on sandpaper in a deployer.

**Comment by Ciruttai** [comment] 2021-12-01 06:55
closed, eternal stella cannot be used on this in the update.

**Closed** 2021-12-01 06:55 UTC
