### ISSUE TITLE
improved backpacks dupe glitch

### ISSUE THREAD

**Issue by willie666687** [simibubi/Above-and-Beyond#388] opened 2022-02-20 10:01 UTC
If I put the backpack on the ground and use the drill break it, it will dupe.
like [https://www.youtube.com/watch?v=BKwGGFWQL0U](url)
not by me

**Comment by UnderscoreKilburn** [comment] 2022-06-04 04:02
Duplicate of #241

**Closed by UnderscoreKilburn** 2022-06-04 04:02 UTC
