### ISSUE TITLE
Urgent Server Crash bug: Forbidden Arcanus Saplings crash server when they grow

### ISSUE THREAD

**Issue by legitswitch** [simibubi/Above-and-Beyond#209] opened 2021-12-01 06:14 UTC
If a sapling from Forbidden Arcanus undergoes growth, the server will crash.

You can use the Item Banning mod to temporarily ban them until the pack updates to the newest version of Forbidden Arcanus.
https://www.curseforge.com/minecraft/mc-mods/item-banning

/itemblacklist ban forbidden_arcanus:cherrywood_sapling
/itemblacklist ban forbidden_arcanus:mysterywood_sapling

**Comment by BD103** [comment] 2021-12-01 11:37
Could you include a log file of the crash for both the server and client?

**Comment by oierbravo** [comment] 2021-12-15 11:08
Duplicate of #237

**Closed** 2022-05-30 04:38 UTC
