### ISSUE TITLE
i swear to god show how to host server exactly with this modpack

### ISSUE THREAD

**Issue by Ewtiz** [simibubi/Above-and-Beyond#359] opened 2022-02-02 20:59 UTC
please

**Comment by ambeeeeee** [comment] 2022-02-03 15:48
Hi, I'm assuming you're using curseforge.

In **My Modpacks**:
![image](https://user-images.githubusercontent.com/4877041/152375919-dcaf7655-d032-4a19-8b6e-f3644d71b4d0.png)
Click "View Profile"

In the resulting screen, click **Download Server Pack**:
![image](https://user-images.githubusercontent.com/4877041/152376119-ce14283e-5aa7-42c4-a7f2-e23180b603ce.png)

**Open the downloaded zip file and extract it**:
![image](https://user-images.githubusercontent.com/4877041/152376301-52e51a9f-54a4-4e71-be81-031479ad0acd.png)

**Run forge-1.16.5-36.2.20-installer.jar**
![image](https://user-images.githubusercontent.com/4877041/152376387-eb776cb0-ce5d-421d-a8b0-a0dbb8498768.png)

**Follow the instructions on the image**
![image](https://user-images.githubusercontent.com/4877041/152376682-ca9843ae-7027-494d-b44c-e37dc6b64e10.png)

[**Please use this guide to configure and run the server**](https://minecraft.fandom.com/wiki/Tutorials/Setting_up_a_Minecraft_Forge_server)

_I am not affiliated with the modpack creator and none of this guide is sanctioned explicitly by them_

**Comment by glektarssza** [comment] 2022-02-04 03:54
Duplicate of #358? Same issue author and same apparent issue.

**Comment by Ewtiz** [comment] 2022-02-04 10:07
> Hi, I'm assuming you're using curseforge.
> 
> In **My Modpacks**: ![image](https://user-images.githubusercontent.com/4877041/152375919-dcaf7655-d032-4a19-8b6e-f3644d71b4d0.png) Click "View Profile"
> 
> In the resulting screen, click **Download Server Pack**: ![image](https://user-images.githubusercontent.com/4877041/152376119-ce14283e-5aa7-42c4-a7f2-e23180b603ce.png)
> 
> **Open the downloaded zip file and extract it**: ![image](https://user-images.githubusercontent.com/4877041/152376301-52e51a9f-54a4-4e71-be81-031479ad0acd.png)
> 
> **Run forge-1.16.5-36.2.20-installer.jar** ![image](https://user-images.githubusercontent.com/4877041/152376387-eb776cb0-ce5d-421d-a8b0-a0dbb8498768.png)
> 
> **Follow the instructions on the image** ![image](https://user-images.githubusercontent.com/4877041/152376682-ca9843ae-7027-494d-b44c-e37dc6b64e10.png)
> 
> [**Please use this guide to configure and run the server**](https://minecraft.fandom.com/wiki/Tutorials/Setting_up_a_Minecraft_Forge_server)
> 
> _I am not affiliated with the modpack creator and none of this guide is sanctioned explicitly by them_

![image](https://user-images.githubusercontent.com/80619183/152510666-296437e6-7ecc-48b9-8acf-5ade75550235.png)
 i get this

**Comment by ambeeeeee** [comment] 2022-02-04 10:13
Upon googling your error, I found [this](https://forums.minecraftforge.net/topic/99364-forge-1165-3612-server-error/).

It looks like you may be running an unsupported version of Java, Please install Java 8 and uninstall any other java versions that you have installed using the "Apps & Features" tab in Windows. If you cannot find it (ie: you're not using Windows 11) please google how to uninstall other java versions.

![image](https://user-images.githubusercontent.com/4877041/152511403-00bfd12b-1973-4800-a5e1-6d958500c091.png)

If you are in an environment where you need a higher java version installed, you can install Java 8 and refer to an online guide on how to use a specific version of Java to launch a program.

In the future, please try googling you error and looking at the search results. Additionally, please be clear about what is wrong when asking for help with a problem.

**Comment by quietust** [comment] 2022-02-04 16:20
If you're running the server on a Windows machine where the Minecraft Client is also installed, you may also be able to use the client's bundled Java 1.8.0_51 runtime to run the server.

**Comment by glektarssza** [comment] 2022-02-04 19:34
You can download Java 8 from the official Java site: https://javadl.oracle.com/webapps/download/AutoDL?BundleId=245477_4d5417147a92418ea8b615e228bb6935

This link is specifically for Java 8u311 which is known to be working at the time of writing. The latest version of Java 8 (8u321) crashes the Forge mod loader right now.

**Comment by BraveCaperCat** [comment] 2022-03-06 21:02
Help me with #396

**Closed** 2022-06-04 03:58 UTC
