### ISSUE TITLE
Can’t combine with my mods and error with mod ftb quests while starting server

### ISSUE THREAD

**Issue by AridGnat3138137** [simibubi/Above-and-Beyond#32] opened 2021-11-03 21:44 UTC
hello i got this error while loading minecraft forge server with FTB quests mod: -- MOD ftbquests --
Details:
    Mod File: ftb-quests-forge-1605.3.5-build.69.jar
    Failure message: FTB Quests (ftbquests) encountered an error during the load_registries event phase
        java.lang.IllegalAccessError: Update to non-static final field net.minecraft.item.Item.field_77700_c attempted from a different method (setCraftingRemainingItemFTBL) than the initializer method <init> 
    Mod Version: 1605.3.5-build.69
    Mod Issue URL: https://github.com/FTBTeam/FTB-Quests/issues
    Exception message: java.lang.IllegalAccessError: Update to non-static final field net.minecraft.item.Item.field_77700_c attempted from a different method (setCraftingRemainingItemFTBL) than the initializer method <init>

**Comment by simibubi** [comment] 2021-11-04 14:02
It looks like its conflicting with another mod. Which ones have you added to the pack?

**Comment by AbiDrew** [comment] 2022-05-17 22:20
Closing this issue since it's caused by something he's trying to add and not inherent to the pack, and he hasn't gotten back to you in months after you asked for more information.

**Closed by AbiDrew** 2022-05-17 22:20 UTC
