### ISSUE TITLE
Create Texture Bug

### ISSUE THREAD

**Issue by Pullermann124** [simibubi/Above-and-Beyond#256] opened 2021-12-19 16:17 UTC
Any Textures relatet to Andesite-, Brass-, Copper-, Shadow- and Radiant Casing are Completly flat (using the Color of the Material)

**Comment by glektarssza** [comment] 2021-12-20 01:56
Are you running Optifine with mipmapping and antialiasing turned on?

I was having the same issue and disabling both of those settings fixed it for me.

**Comment by glektarssza** [comment] 2021-12-20 01:57
Possibly duplicate of #119

**Closed** 2022-05-30 04:36 UTC
Labels: mod issue
