### ISSUE TITLE
Server crashing after updating from 1.0 to 1.2

### ISSUE THREAD

**Issue by Ristorff** [simibubi/Above-and-Beyond#220] opened 2021-12-04 06:21 UTC
Here's the crash report.
[crash-2021-12-04_13.34.48-server.txt](https://github.com/simibubi/Above-and-Beyond/files/7653467/crash-2021-12-04_13.34.48-server.txt)

**Comment by DivineJr** [comment] 2021-12-05 22:56
I'm having the exact same issue, it's not the upgrade from 1.0 to 1.2, but 1.2 itself. Completely new server on 1.2 with no old data from 1.0 and I'm having either the exact same or extremely similar issue.
Including my crash log with nearly the same issue in case it helps


[crash-2021-12-05_17.54.51-server.txt](https://github.com/simibubi/Above-and-Beyond/files/7656959/crash-2021-12-05_17.54.51-server.txt)

**Comment by tim661811** [comment] 2021-12-06 18:47
I also have the same issue. It started happening for me after updating from v1.1 to update v1.2.

[crash-2021-12-03_12.29.38-server.txt](https://github.com/simibubi/Above-and-Beyond/files/7662854/crash-2021-12-03_12.29.38-server.txt)

**Comment by VulpTheHorseDog** [comment] 2021-12-09 03:31
Same issue here. Best I can get from it is there's an illegal cast from DecoratedFeatureConfig to BaseTreeFeatureConfig. Unfortunately the log doesn't give too much more info on it.

**Comment by TigerWalts** [comment] 2021-12-09 17:29
I suspect that this may have been caused by Forbidden and Arcanus and it may be fixed in 16.2.2

- https://github.com/stal111/Forbidden-Arcanus/commit/047612c48c21df9bdd2ea3c52cd20aaee1acab1c

**Comment by tim661811** [comment] 2021-12-10 15:35
> I suspect that this may have been caused by Forbidden and Arcanus and it may be fixed in 16.2.2
> 
> * [stal111/Forbidden-Arcanus@047612c](https://github.com/stal111/Forbidden-Arcanus/commit/047612c48c21df9bdd2ea3c52cd20aaee1acab1c)


I can confirm that updating the forbidden and arcanus mod to 16.2.2 indeed fixes the issue. My server has been running for 24hrs now without any crashes!

**Comment by Ristorff** [comment] 2021-12-13 02:17
> I suspect that this may have been caused by Forbidden and Arcanus and it may be fixed in 16.2.2
> 
> * [stal111/Forbidden-Arcanus@047612c](https://github.com/stal111/Forbidden-Arcanus/commit/047612c48c21df9bdd2ea3c52cd20aaee1acab1c)

Tried to update it to 16.2.2 but my server still crashes. :(

**Closed** 2022-06-04 03:37 UTC
