### ISSUE TITLE
Chain Recipe

### ISSUE THREAD

**Issue by KiJ00** [simibubi/Above-and-Beyond#168] opened 2021-11-20 23:05 UTC
The recipe for the "Chain" is overwritten by the recipe for "Iron Chain" from the mod "Forbidden & Arcanus".

**Comment by GE0NE** [comment] 2021-11-22 13:20
Duplicate of #95

**Comment by corintho** [comment] 2021-12-04 13:22
Fixed on 1.2:
`Fixed a recipe conflict between forbidden arcanus and ..vanilla minecraft`
Now, the recipe will craft a vanilla chain, and you can put the vanilla chain alone in the crafting grid to get 3 F&A chains

**Closed** 2022-05-25 02:31 UTC
